version: '3.7'

services:
  db:
    container_name: fs20_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5435:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redisdata:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: