export * from './google.strategy'
export * from './jwt.strategy'
export * from './facebook.strategy'
export * from './instagram.strategy'
export * from './linkedin.strategy'
export * from './telegram.strategy'
export * from './api-jwt.strategy'